# Generated by Django 3.2.7 on 2021-09-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210907_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
