# Generated by Django 3.2.7 on 2021-09-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(blank=True, max_length=100)),
                ('away_tem', models.CharField(blank=True, max_length=100)),
                ('league', models.CharField(blank=True, max_length=100)),
                ('tip', models.CharField(blank=True, max_length=20)),
                ('odds', models.CharField(blank=True, max_length=20)),
                ('result', models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30)),
            ],
        ),
    ]
