# Generated by Django 3.2.7 on 2021-09-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_vipgames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipgames',
            old_name='away_tem',
            new_name='away_team',
        ),
    ]
