# Generated by Django 3.2.7 on 2021-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_away_tem_vipgames_away_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
