# Generated by Django 3.2.7 on 2021-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_vipgames_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipgames',
            name='league',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
