# Generated by Django 3.2.7 on 2021-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210920_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipgames',
            name='away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='dB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='vipgames',
            name='tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
