# Generated by Django 3.2.7 on 2021-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210920_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipgames',
            old_name='dA_result',
            new_name='d_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='dB_result',
            new_name='t_result',
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
