# Generated by Django 3.2.7 on 2021-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20210920_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipgames',
            name='fA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='f_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffE_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffE_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffE_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffE_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffE_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ff_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='gF_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='gF_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='gF_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='gF_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='gF_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sE_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sE_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sE_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sE_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sE_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sF_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sF_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sF_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sF_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sF_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='s_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siE_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siE_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siE_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siE_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siE_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siF_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siF_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siF_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siF_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siF_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='si_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
    ]
