# Generated by Django 3.2.7 on 2021-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210920_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipgames',
            name='ccA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccE_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccE_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccE_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccE_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccE_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccF_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccF_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccF_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccF_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccF_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccG_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccG_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccG_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccG_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccG_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccH_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccH_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccH_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccH_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccH_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccI_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccI_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccI_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccI_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccI_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccJ_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccJ_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccJ_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccJ_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccJ_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='cc_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftE_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftE_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftE_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftE_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftE_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftF_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftF_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftF_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftF_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftF_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftG_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftG_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftG_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftG_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftG_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftH_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftH_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftH_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftH_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftH_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftI_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftI_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftI_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftI_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftI_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftJ_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftJ_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftJ_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftJ_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftJ_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ft_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggE_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggE_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggE_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggE_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggE_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggF_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggF_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggF_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggF_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggF_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggG_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggG_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggG_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggG_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggG_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggH_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggH_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggH_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggH_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggH_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggI_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggI_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggI_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggI_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggI_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggJ_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggJ_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggJ_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggJ_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggJ_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='gg_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htA_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htA_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htA_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htA_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htA_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htB_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htB_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htB_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htB_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htB_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htC_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htC_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htC_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htC_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htC_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htD_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htD_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htD_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htD_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htD_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htE_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htE_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htE_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htE_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htE_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htF_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htF_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htF_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htF_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htF_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htG_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htG_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htG_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htG_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htG_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htH_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htH_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htH_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htH_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htH_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htI_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htI_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htI_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htI_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htI_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htJ_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htJ_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htJ_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htJ_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htJ_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ht_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
    ]
