# Generated by Django 3.2.7 on 2021-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210920_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipgames',
            old_name='cc_result',
            new_name='a_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='f_result',
            new_name='b_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='ff_result',
            new_name='c_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='ft_result',
            new_name='ccA_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='gg_result',
            new_name='ccB_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='ht_result',
            new_name='ccC_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='s_result',
            new_name='ccD_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='si_result',
            new_name='ccE_result',
        ),
        migrations.RenameField(
            model_name='vipgames',
            old_name='t_result',
            new_name='ccF_result',
        ),
        migrations.AddField(
            model_name='vipgames',
            name='a_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='a_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='a_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='a_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='a_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='b_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='b_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='b_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='b_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='b_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='c_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='c_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='c_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='c_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='c_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccG_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccH_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccI_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ccJ_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='dA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='dB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='d_away_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='d_home_team',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='d_league',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='d_odds',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='d_tip',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='fD_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffD_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ffE_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftD_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftE_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftF_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftG_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftH_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftI_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ftJ_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='gf_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggD_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggE_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggF_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggG_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggH_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='ggJ_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htD_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htE_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htF_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htG_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htH_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htI_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='htJ_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sD_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sE_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='sF_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siD_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siE_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='siF_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tA_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tB_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='vipgames',
            name='tC_result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
    ]
