# Generated by Django 3.2.7 on 2021-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_vipgames_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipgames',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
